apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "database.fullname" . }}
  name: {{ include "database.fullname" . }}
spec:
  selector:
    app: {{ include "database.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379