apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "database.fullname" . }}-pv
  labels:
    type: local
spec:
  storageClassName: {{ include "database.fullname" . }}-sc
  capacity:
    storage: {{ .Values.volume.storage }} 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  /mnt/data/{{ .Release.Name }}