name: Terraform Apply

on:
  workflow_dispatch:

  push:
    paths:
      - "terraform/environments/dev/**"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environments/dev

      - name: Terraform Apply
        run: terraform plan -var="ci_user_id=${{ secrets.AWS_USER_ID }}" -var="ci_user_name=${{ secrets.AWS_USER_NAME }}"
        working-directory: terraform/environments/dev
