name: DEV - Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: infrastructure/environments/dev/terraform

      - name: Create resources
        run: terraform apply -var="ci_user_id=${{ secrets.AWS_USER_ID }}" -var="ci_user_name=${{ secrets.AWS_USER_NAME }}" -auto-approve
        working-directory: infrastructure/environments/dev/terraform

      - name: Install Kubernetes CLI
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Check Cluster Connection
        run: |
          aws eks update-kubeconfig --name counter-app-development-eks-cluster --region ${{ secrets.AWS_REGION }}
          kubectl get all

      - name: Install Ingress
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.0/deploy/static/provider/cloud/deploy.yaml

      - name: Point Domain to Ingress ALB
        working-directory: infrastructure/environments/dev/dns
        run: |
          ALB_ENDPOINT=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')

          echo "ALB ENDPOINT: $ALB_ENDPOINT"

          HOSTED_ZONE_ID=$(aws route53 list-hosted-zones --query "HostedZones[?Name=='mindaugasl.com.'].Id" --output text)

          # Replace the ALB_ENDPOINT in cname.json
          sed -i "s|\$ALB_ENDPOINT|$ALB_ENDPOINT|g" ./cname.json

          aws route53 change-resource-record-sets \
          --hosted-zone-id $HOSTED_ZONE_ID \
          --change-batch file://./cname.json
