name: DEV - Build Backend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check docker
        run: docker -v

      # - name: Log in to Registry
      #   run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 009160063900.dkr.ecr.eu-central-1.amazonaws.com
