name: DEV - Build Frontend

on:
  workflow_dispatch:

jobs:
  build-and-publish-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codee
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker Image
        run: docker build --platform linux/amd64 --build-arg="VITE_API_URL=http://dev.api.mindaugasl.com/api" -t dev-counter-frontend .
        working-directory: apps/frontend

      - name: Log in to ECR Registry
        run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 009160063900.dkr.ecr.eu-central-1.amazonaws.com

      - name: Tag Docker Image
        run: docker tag dev-counter-frontend ${{ secrets.AWS_USER_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/counter-app:dev-frontend-latest

      - name: Push Docker Image
        run: docker push ${{ secrets.AWS_USER_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/counter-app:dev-frontend-latest
