name: DEV - Deploy Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add EKS Cluster
        run: aws eks update-kubeconfig --name counter-app-development-eks-cluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy Application
        working-directory: infrastructure/environments/dev/k8s
        run: |
          helm install dev chart \
          --set aws.userId=${{ secrets.AWS_USER_ID }} \
          --set aws.region=${{ secrets.AWS_REGION }} \
          --set aws.ecrPassword=$(aws ecr get-login-password --region ${{ secrets.AWS_REGION }})
